"""
Centralized State Management Module for the Agentic Loop.

Defines the strictly typed SharedState containing explicit fields for evaluation
auditability and deterministic handoffs between LangGraph nodes.
"""

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class SharedState(BaseModel):
    """
    Main state object preserved across all agent node handoffs in LangGraph.

    The model deliberately keeps each workflow artifact in a named field so
    that orchestration, auditing, and human review can inspect the loop without
    relying on untyped dictionaries or hidden agent context.
    """

    patient_id: str = Field(
        default="",
        description="Unique identifier for the patient under tracking.",
    )
    raw_symptoms: str = Field(
        default="",
        description="Unstructured user or patient-provided clinical description.",
    )
    extracted_symptoms: List[str] = Field(
        default_factory=list,
        description="Structured symptoms parsed by the triage agent.",
    )
    medical_research_data: str = Field(
        default="",
        description="Relevant reference data fetched from MCP tools and vectors.",
    )
    initial_diagnosis: str = Field(
        default="",
        description="Primary candidate diagnostic report generated by the diagnostic agent.",
    )
    critic_feedback: str = Field(
        default="",
        description="Iterative engineering review commentary provided by the critic node.",
    )
    retry_count: int = Field(
        default=0,
        description="Counter tracking active self-healing feedback rounds (maximum 3).",
        ge=0,
    )
    compliance_status: str = Field(
        default="PENDING",
        description="Evaluated state for PII safety, constraints, and legal boundaries.",
    )
    final_clinical_report: str = Field(
        default="",
        description="Fully vetted, safe clinical output compiled for deployment.",
    )
    token_usage_log: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Audit ledger for input/output tokens and cost tracking.",
    )
    current_step: str = Field(
        default="START",
        description="Live status metric for terminal visualization dashboards.",
    )
    hitl_approved: Optional[bool] = Field(
        default=None,
        description="Human override selection state from the user checkpoint loop.",
    )